create table film_genre (
  film_id uuid not null,
  genre_id integer not null,
  constraint film_genre_pkey primary key (film_id, genre_id),
  constraint film_genre_film foreign key (film_id)
    references films (film_id) match simple
    on update no action
    on delete no action
    not valid,
  constraint film_genre_genre foreign key (genre_id)
    references genres (genre_id) match simple
    on update no action
    on delete no action
    not valid
);


create table productions (
  production_id integer not null primary key generated by default as identity,
  film_id uuid not null,
  societe_id uuid not null,
   constraint production_films_fk foreign key (film_id)
        references films (film_id) match simple
        on update no action
        on delete no action
        not valid,
  constraint production_societes_fk foreign key (societe_id)
        references societes (societe_id) match simple
        on update no action
        on delete no action
        not valid
);
