create table franchises (
  franchise_id integer not null primary key generated by default as identity,
  franchise text not null
);

create table societes (
  societe_id uuid default gen_random_uuid() not null primary key,
  societe text not null
);

create table certifications (
  certification_id integer,
  pays text,
  ordre smallint,
  certification text,
  description text
);
