create table salles (
  salle_id integer not null primary key generated by default as identity,
  etablissement_id integer not null,
  salle text not null,
  sieges integer not null
);

alter table
  add constraint salle_etablissement_fk foreign key (etablissement_id)
        references etablissements (etablissement_id) match simple
        on update no action
        on delete no action
        not valid;

create table seances (
 seance_id integer not null primary key generated by default as identity,
  film_id uuid not null,
  salle_id integer not null,
  seance date not null,
  constraint seance_salle_fk foreign key (salle_id)
    references salles (salle_id) match simple
    on update no action
    on delete no action
    not valid,
  constraint seance_film_fk foreign key (film_id)
    references films (film_id) match simple
    on update no action
    on delete no action
    not valid
);
